FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /code
ENV PATH=$PATH:/root/.dotnet/tools

COPY . .

RUN apt-get update && apt-get install libxml2
RUN dotnet tool install --global dotnet-sonarscanner
RUN dotnet tool install --global dotnet-coverage

RUN dotnet sonarscanner begin /k:"{app_key}" /d:sonar.token="{app_token}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml /d:sonar.host.url="{sonar_host}:{sonar_port}" /d:sonar.coverage.exclusions={exclude}
RUN dotnet build --no-incremental
RUN dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
RUN dotnet sonarscanner end /d:sonar.token="{app_token}"
